modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="lefameuxmod"
version="1.0.0"
displayName="LeFameuxMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Anthony, MCreator"

[[dependencies.lefameuxmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



